version: '3'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=postgresql://quizdb:quizdb@db:5432/quizdb
      - REDIS_URL=redis://redis:6379/0

  celery_worker:
    build: .
    command: celery -A app.celery_queue.celery_app.celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=postgresql://quizdb:quizdb@db:5432/quizdb
      - REDIS_URL=redis://redis:6379/0

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: quizdb
      POSTGRES_PASSWORD: quizdb
      POSTGRES_DB: quizdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
